app:
  timezone: "Asia/Almaty"
  outbox_dir: "outbox"
  backups_dir: "backups"

db:
  driver: "sqlite"
  uri: "sqlite:///erp.db"   # Expert decision: start with SQLite for ops simplicity; Postgres is upgrade path.

paths:
  xlsx_sku_map: "/Users/adil/Documents/useful tables/Main crm spreadsheets/main tables/Sku_Map_CRM_3.xlsx"
  xlsx_sales:   "/Users/adil/Documents/useful tables/Main crm spreadsheets/main tables/SALES_KSP_CRM_GPT_15.9.25.xlsx"
  xlsx_demand:  "/Users/adil/Documents/useful tables/GPT/gpt files/Inventory_mahangement/branch_V2.3/4.10.25 PO's/New_D_2X_size_wide_4.10.25.xlsx"
  xlsx_business_model: "/Users/adil/Documents/useful tables/Main crm spreadsheets/main tables/Business_model_V3.xlsx"
  xlsx_sales_v3: "/Users/adil/Docs/kaspi_etl/docs/ops/kaspi/SALES_KSP_CRM_V3.xlsx"
  xlsx_delivery_bands: "/Users/adil/Documents/useful tables/GPT/gpt files/Inventory_mahangement/branch_V2.3/4.10.25 PO's/secondary files/KSP_Delivery_rates_V5.xlsx"

feature_flags:
  enable_flow_A_orders_whatsapp: false
  enable_flow_B_inventory_oos: true
