# CONFIG.example.yaml — copy to CONFIG.yaml and edit (never commit secrets)

app:
  timezone: "Asia/Almaty"
  outbox_dir: "outbox"
  backups_dir: "backups"

db:
  driver: "sqlite"
  uri: "sqlite:///erp.db"  # later: postgres://user:pass@host/db

kaspi:
  accounts:
    - name: "UNIVERSAL"
      account_id: "KSP_ACCT_1"
      auth: "${KASPI_TOKEN_UNIVERSAL}"
    - name: "ONLYFIT"
      account_id: "KSP_ACCT_2"
      auth: "${KASPI_TOKEN_ONLYFIT}"
  poll_interval_min: 15

whatsapp:
  provider: "algatop"  # later: cloud/twilio
  from_number: "+70000000000"
  webhook_secret: "${WA_WEBHOOK_SECRET}"

policy:
  L_days: 16
  R_days: 7
  B_days: 14
  z_service: 1.65
  tv_floor: 0.23
  vat_pct: 0.03
  platform_pct: 0.12
  delivery_blend_city: 0.35
  delivery_blend_country: 0.65

paths:
  xlsx_sku_map: "data_raw/Sku_Map_CRM_3.xlsx"
  xlsx_sales: "data_raw/SALES_KSP_CRM_GPT_15.9.25.xlsx"
  xlsx_demand: "data_raw/New_D_2X_size_wide_4.10.25.xlsx"
  xlsx_delivery_bands: "data_raw/KSP_Delivery_rates_V5.xlsx"
  xlsx_catalog: "data_raw/Business_model_V3.xlsx"

feature_flags:
  enable_flow_A_orders_whatsapp: false
  enable_flow_B_inventory_oos: true
